name: First CI Test

on:
  push:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Скачать код
        uses: actions/checkout@v4

      - name: Проверка CI
        run: echo "CI работает!"
