name: PHP CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install NPM dependencies
        run: npm install

      - name: Build assets
        run: npm run build

      - name: Prepare environment
        run: |
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          php artisan key:generate --force

      - name: Run Laravel Pint
        run: ./vendor/bin/pint --test

      - name: Run tests
        run: php artisan test
